services:
  - type: web
    name: flask-api1-mobilenetv2
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: PORT
        value: 5000
